# this is the name of the workflow that will be displayed in the Actions tab
name: TEST1

# Manual click (deliver) workflow whenever the user needs
on: 
  workflow_dispatch:

jobs:

  info:
    runs-on: ubuntu-latest
    steps:
      - name: checkout os version
        run: cat /etc/os-release
    
      - name: host information
        run: hostname
